#!/bin/sh

# inspired by https://blog.dbi-services.com/using-tmux-for-semi-interactive-demos/
# alternatives: https://doitlive.readthedocs.io

set -e

TMUX_DEMO_SCRIPT="$1"

test -r "${TMUX_DEMO_SCRIPT}" || exit 1

tmux set-environment TMUX_DEMO_SCRIPT "${TMUX_DEMO_SCRIPT}"
tmux set-environment TMUX_DEMO_LINE 1

tmux bind-key -T root C-PageDown run-shell tmux-demo-next
tmux bind-key -T root C-PageUp run-shell tmux-demo-previous
