#!/bin/sh

set -e

PLUSORMINUS="+"

if [ "$(basename $0)" = "tmux-demo-previous" ];then
  PLUSORMINUS="-"
fi

eval $(tmux show-environment TMUX_DEMO_LINE)
eval $(tmux show-environment TMUX_DEMO_SCRIPT)

tmux set-environment TMUX_DEMO_LINE $(expr ${TMUX_DEMO_LINE} ${PLUSORMINUS} 1)
SCRIPT_LENGTH=$(cat ${TMUX_DEMO_SCRIPT}|wc -l)

if [ $(expr 2 + ${SCRIPT_LENGTH}) -lt ${TMUX_DEMO_LINE} ]; then
  LINE="#line out of range: ${TMUX_DEMO_LINE}"
else
  LINE="$(sed -n ${TMUX_DEMO_LINE}p ${TMUX_DEMO_SCRIPT} || echo "#line below 1: ${TMUX_DEMO_LINE}")"
fi

if [ "x" = "x${LINE}" ]; then
  exec $0
fi

tmux send-keys "${LINE}"
